print "Content-type:text/html\r\n\r\n"
print "<html>"
print "<head>"
print "<title>Hello Soul Society! - First CGI Program</title>"
print "</head>"
print "<body>"
print "<h2>Hello Soul Society! This is my first CGI program</h2>"
print "</body>"
print "</html>"